<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Assignment 1 – Enzel Ege Sarı’s Analytics Lab</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assignments/assignment-2.html" rel="next">
<link href="../assignments.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Enzel Ege Sarı’s Analytics Lab</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">Hey, it’s me!</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../posts.html"> 
<span class="menu-text">My Posts</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-emu660-coursework" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">EMU660 Coursework</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-emu660-coursework">    
        <li>
    <a class="dropdown-item" href="../assignments.html">
 <span class="dropdown-text">Assignments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../project.html">
 <span class="dropdown-text">Project</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://github.com/Selenzel" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/in/enzel-ege-sari/" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-linkedin"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../assignments/assignment-1.html">Assignment 1</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">My Assignments</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/assignment-1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Assignment 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/assignment-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 2</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignment-1" id="toc-assignment-1" class="nav-link active" data-scroll-target="#assignment-1">Assignment 1</a>
  <ul class="collapse">
  <li><a href="#a-brief-summary-of-baykal" id="toc-a-brief-summary-of-baykal" class="nav-link" data-scroll-target="#a-brief-summary-of-baykal">(a) Brief Summary of Baykal</a></li>
  <li><a href="#b-a-basic-computation-using-mtcars" id="toc-b-a-basic-computation-using-mtcars" class="nav-link" data-scroll-target="#b-a-basic-computation-using-mtcars">(b) A Basic Computation Using “mtcars”</a></li>
  <li><a href="#c-having-fun-with-na_example" id="toc-c-having-fun-with-na_example" class="nav-link" data-scroll-target="#c-having-fun-with-na_example">(c) Having Fun with “NA_Example”</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="assignment-1" class="level1">
<h1>Assignment 1</h1>
<pre><code></code></pre>
<p>My first assignment has two parts.</p>
<section id="a-brief-summary-of-baykal" class="level2">
<h2 class="anchored" data-anchor-id="a-brief-summary-of-baykal">(a) Brief Summary of Baykal</h2>
<p>He is really friendly and shared his own thoughts about this type of engagements with students and how he would wanted some to introduce what his job life looks like.</p>
<p>In the first section he talked about his experiences after the graduation. Eve though he graduated from Industrial engineering he started to work in the software industry. In his current job he is working in the sales of the developed OR system but he is more technical side of this sales business.</p>
<p>In the second part he discussed what is OR is in the modern technology. The general industry is now focuses more on the AI and Machine Learning rather than the OR itself. Now we can more see the analytics instead of the OR/optimization. He mentioned that the analytics can be observed on 4 main fields. The most basic one is the descriptive analytics which just shows what the data is, second is diagnostic analytics which analyses the root causes of the problems, predictive analytics focuses on the future possibilities and lastly the prescriptive analytics focuses on the action of the resolving the root causes. He also mentioned the tools that can be used for each analytic analyzes. These analytic method can be used together (also this is encouraged). Using all these method together will help to analyze problem, find the root cause and find a solution.</p>
<p>Lastly he mentioned how we can project-ify these methods and how to understand the KPI’s. He also encouraged us the deploy the projects we have. This will show what is missing with the project what can be done to improve. The user is the king approach will help with our final outcome.</p>
</section>
<section id="b-a-basic-computation-using-mtcars" class="level2">
<h2 class="anchored" data-anchor-id="b-a-basic-computation-using-mtcars">(b) A Basic Computation Using “mtcars”</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>compute_stats <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">Mean =</span> <span class="fu">mean</span>(x), <span class="at">Median =</span> <span class="fu">median</span>(x), <span class="at">Variance=</span><span class="fu">var</span>(x), <span class="at">InterQuartileRange=</span><span class="fu">IQR</span>(x), <span class="at">Minimum =</span> <span class="fu">min</span>(x), </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">Maximum =</span> <span class="fu">max</span>(x))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sapply</span>(mtcars,compute_stats),<span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   mpg      cyl      disp     hp       drat      wt      
Mean               20.09062 6.1875   230.7219 146.6875 3.596563  3.21725 
Median             19.2     6        196.3    123      3.695     3.325   
Variance           36.3241  3.189516 15360.8  4700.867 0.2858814 0.957379
InterQuartileRange 7.375    4        205.175  83.5     0.84      1.02875 
Minimum            10.4     4        71.1     52       2.76      1.513   
Maximum            33.9     8        472      335      4.93      5.424   
                   qsec     vs        am        gear      carb    
Mean               17.84875 0.4375    0.40625   3.6875    2.8125  
Median             17.71    0         0         4         2       
Variance           3.193166 0.2540323 0.2489919 0.5443548 2.608871
InterQuartileRange 2.0075   1         1         1         2       
Minimum            14.5     0         0         3         1       
Maximum            22.9     1         1         5         8       </code></pre>
</div>
</div>
</section>
<section id="c-having-fun-with-na_example" class="level2">
<h2 class="anchored" data-anchor-id="c-having-fun-with-na_example">(c) Having Fun with “NA_Example”</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dslabs)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"na_example"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>na_example</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   [1]  2  1  3  2  1  3  1  4  3  2  2 NA  2  2  1  4 NA  1  1  2  1  2  2  1
  [25]  2  5 NA  2  2  3  1  2  4  1  1  1  4  5  2  3  4  1  2  4  1  1  2  1
  [49]  5 NA NA NA  1  1  5  1  3  1 NA  4  4  7  3  2 NA NA  1 NA  4  1  2  2
  [73]  3  2  1  2  2  4  3  4  2  3  1  3  2  1  1  1  3  1 NA  3  1  2  2  1
  [97]  2  2  1  1  4  1  1  2  3  3  2  2  3  3  3  4  1  1  1  2 NA  4  3  4
 [121]  3  1  2  1 NA NA NA NA  1  5  1  2  1  3  5  3  2  2 NA NA NA NA  3  5
 [145]  3  1  1  4  2  4  3  3 NA  2  3  2  6 NA  1  1  2  2  1  3  1  1  5 NA
 [169] NA  2  4 NA  2  5  1  4  3  3 NA  4  3  1  4  1  1  3  1  1 NA NA  3  5
 [193]  2  2  2  3  1  2  2  3  2  1 NA  2 NA  1 NA NA  2  1  1 NA  3 NA  1  2
 [217]  2  1  3  2  2  1  1  2  3  1  1  1  4  3  4  2  2  1  4  1 NA  5  1  4
 [241] NA  3 NA NA  1  1  5  2  3  3  2  4 NA  3  2  5 NA  2  3  4  6  2  2  2
 [265] NA  2 NA  2 NA  3  3  2  2  4  3  1  4  2 NA  2  4 NA  6  2  3  1 NA  2
 [289]  2 NA  1  1  3  2  3  3  1 NA  1  4  2  1  1  3  2  1  2  3  1 NA  2  3
 [313]  3  2  1  2  3  5  5  1  2  3  3  1 NA NA  1  2  4 NA  2  1  1  1  3  2
 [337]  1  1  3  4 NA  1  2  1  1  3  3 NA  1  1  3  5  3  2  3  4  1  4  3  1
 [361] NA  2  1  2  2  1  2  2  6  1  2  4  5 NA  3  4  2  1  1  4  2  1  1  1
 [385]  1  2  1  4  4  1  3 NA  3  3 NA  2 NA  1  2  1  1  4  2  1  4  4 NA  1
 [409]  2 NA  3  2  2  2  1  4  3  6  1  2  3  1  3  2  2  2  1  1  3  2  1  1
 [433]  1  3  2  2 NA  4  4  4  1  1 NA  4  3 NA  1  3  1  3  2  4  2  2  2  3
 [457]  2  1  4  3 NA  1  4  3  1  3  2 NA  3 NA  1  3  1  4  1  1  1  2  4  3
 [481]  1  2  2  2  3  2  3  1  1 NA  3  2  1  1  2 NA  2  2  2  3  3  1  1  2
 [505] NA  1  2  1  1  3  3  1  3  1  1  1  1  1  2  5  1  1  2  2  1  1 NA  1
 [529]  4  1  2  4  1  3  2 NA  1  1 NA  2  1  1  4  2  3  3  1  5  3  1  1  2
 [553] NA  1  1  3  1  3  2  4 NA  2  3  2  1  2  1  1  1  2  2  3  1  5  2 NA
 [577]  2 NA  3  2  2  2  1  5  3  2  3  1 NA  3  1  2  2  2  1  2  2  4 NA  6
 [601]  1  2 NA  1  1  2  2  3 NA  3  2  3  3  4  2 NA  2 NA  4 NA  1  1  2  2
 [625]  3  1  1  1  3 NA  2  5 NA  7  1 NA  4  3  3  1 NA  1  1  1  1  3  2  4
 [649]  2  2  3 NA NA  1  4  3  2  2  2  3  2  4  2  2  4 NA NA NA  6  3  3  1
 [673]  4  4  2  1 NA  1  6 NA  3  3  2  1  1  6 NA  1  5  1 NA  2  6  2 NA  4
 [697]  1  3  1  2 NA  1  1  3  1  2  4  2  1  3  2  4  3  2  2  1  1  5  6  4
 [721]  2  2  2  2  4 NA  1  2  2  2  2  4  5 NA NA NA  4  3  3  3  2  4  2  4
 [745] NA NA NA NA  2  1 NA  2  4  3  2 NA  2  3  1  3  4 NA  1  2  1  2 NA  3
 [769]  1  2  1  2  1  2  1  2  2  2  2  1  1  3  3  1  3  4  3 NA NA  4  2  3
 [793]  2  1  3  2  4  2  2  3  1  2  4  3  3  4 NA  1  4  2  1  1  1  3  1  5
 [817]  2  2  4  2 NA  1  3  1  2 NA  1  2  1  2  1 NA  1  3  2  3  2 NA  2  1
 [841]  4  2 NA NA NA  2  4  2 NA NA  3  1 NA  5  5  2  2  2 NA  2  1  3  1  3
 [865]  2  4  2  4 NA  4  1  2  3  2  3  3  2  3  2  2  2  1  3  2  4  2 NA  3
 [889]  3  2  2 NA NA  3  2  1  2  4  1  1  1  1  4  3  2 NA  3  2 NA  1 NA  3
 [913]  2  1  1  1  2 NA  2  2  3  3  2 NA NA  4  5  2  2  2  1  2  3  1  3  3
 [937]  4  3 NA  1  1  1 NA  4  3  5  1  1  2 NA  2  2  2  2  5  2  2  3  1  2
 [961]  3 NA  1  2 NA NA  2 NA  3  1  1  2  5  3  5  1  1  4 NA  2  1  3  1  1
 [985]  2  4  3  3  3 NA  1  1  2  2  1  1  2  2 NA  2</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>TotalNA <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(na_example))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>IndexNA <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">is.na</span>(na_example))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>strNA <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">'NA '</span>,<span class="st">'Amount '</span>,<span class="st">'-&gt; '</span>,TotalNA,<span class="st">'</span><span class="sc">\n</span><span class="st">'</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(strNA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "NA Amount -&gt; 145\n"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">'Indeces of the NAs -&gt; '</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Indeces of the NAs -&gt; "</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(IndexNA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  12  17  27  50  51  52  59  65  66  68  91 117 125 126 127 128 139 140
 [19] 141 142 153 158 168 169 172 179 189 190 203 205 207 208 212 214 237 241
 [37] 243 244 253 257 265 267 269 279 282 287 290 298 310 325 326 330 341 348
 [55] 361 374 392 395 397 407 410 437 443 446 461 468 470 490 496 505 527 536
 [73] 539 553 561 576 578 589 599 603 609 616 618 620 630 633 636 641 652 653
 [91] 666 667 668 677 680 687 691 695 701 726 734 735 736 745 746 747 748 751
[109] 756 762 767 788 789 807 821 826 832 838 843 844 845 849 850 853 859 869
[127] 887 892 893 906 909 911 918 924 925 939 943 950 962 965 966 968 979 990
[145] 999</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(na_example,<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>stdev <span class="ot">&lt;-</span> <span class="fu">sd</span>(na_example, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>meanStr <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">'Mean (w/o NA) -&gt;'</span>,mean)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>stdevStr <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">'Standart deviation (w/o NA) -&gt;'</span>,stdev)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(meanStr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mean (w/o NA) -&gt;2.30175438596491"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(stdevStr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Standart deviation (w/o NA) -&gt;1.22338043224169"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(na_example,<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>arr1 <span class="ot">&lt;-</span> na_example</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>arr1[<span class="fu">is.na</span>(na_example)] <span class="ot">&lt;-</span> mean</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>arr1Str <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">'New Dataset With Mean Replacing NAs'</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(arr1Str)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "New Dataset With Mean Replacing NAs"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(arr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   [1] 2.000000 1.000000 3.000000 2.000000 1.000000 3.000000 1.000000 4.000000
   [9] 3.000000 2.000000 2.000000 2.301754 2.000000 2.000000 1.000000 4.000000
  [17] 2.301754 1.000000 1.000000 2.000000 1.000000 2.000000 2.000000 1.000000
  [25] 2.000000 5.000000 2.301754 2.000000 2.000000 3.000000 1.000000 2.000000
  [33] 4.000000 1.000000 1.000000 1.000000 4.000000 5.000000 2.000000 3.000000
  [41] 4.000000 1.000000 2.000000 4.000000 1.000000 1.000000 2.000000 1.000000
  [49] 5.000000 2.301754 2.301754 2.301754 1.000000 1.000000 5.000000 1.000000
  [57] 3.000000 1.000000 2.301754 4.000000 4.000000 7.000000 3.000000 2.000000
  [65] 2.301754 2.301754 1.000000 2.301754 4.000000 1.000000 2.000000 2.000000
  [73] 3.000000 2.000000 1.000000 2.000000 2.000000 4.000000 3.000000 4.000000
  [81] 2.000000 3.000000 1.000000 3.000000 2.000000 1.000000 1.000000 1.000000
  [89] 3.000000 1.000000 2.301754 3.000000 1.000000 2.000000 2.000000 1.000000
  [97] 2.000000 2.000000 1.000000 1.000000 4.000000 1.000000 1.000000 2.000000
 [105] 3.000000 3.000000 2.000000 2.000000 3.000000 3.000000 3.000000 4.000000
 [113] 1.000000 1.000000 1.000000 2.000000 2.301754 4.000000 3.000000 4.000000
 [121] 3.000000 1.000000 2.000000 1.000000 2.301754 2.301754 2.301754 2.301754
 [129] 1.000000 5.000000 1.000000 2.000000 1.000000 3.000000 5.000000 3.000000
 [137] 2.000000 2.000000 2.301754 2.301754 2.301754 2.301754 3.000000 5.000000
 [145] 3.000000 1.000000 1.000000 4.000000 2.000000 4.000000 3.000000 3.000000
 [153] 2.301754 2.000000 3.000000 2.000000 6.000000 2.301754 1.000000 1.000000
 [161] 2.000000 2.000000 1.000000 3.000000 1.000000 1.000000 5.000000 2.301754
 [169] 2.301754 2.000000 4.000000 2.301754 2.000000 5.000000 1.000000 4.000000
 [177] 3.000000 3.000000 2.301754 4.000000 3.000000 1.000000 4.000000 1.000000
 [185] 1.000000 3.000000 1.000000 1.000000 2.301754 2.301754 3.000000 5.000000
 [193] 2.000000 2.000000 2.000000 3.000000 1.000000 2.000000 2.000000 3.000000
 [201] 2.000000 1.000000 2.301754 2.000000 2.301754 1.000000 2.301754 2.301754
 [209] 2.000000 1.000000 1.000000 2.301754 3.000000 2.301754 1.000000 2.000000
 [217] 2.000000 1.000000 3.000000 2.000000 2.000000 1.000000 1.000000 2.000000
 [225] 3.000000 1.000000 1.000000 1.000000 4.000000 3.000000 4.000000 2.000000
 [233] 2.000000 1.000000 4.000000 1.000000 2.301754 5.000000 1.000000 4.000000
 [241] 2.301754 3.000000 2.301754 2.301754 1.000000 1.000000 5.000000 2.000000
 [249] 3.000000 3.000000 2.000000 4.000000 2.301754 3.000000 2.000000 5.000000
 [257] 2.301754 2.000000 3.000000 4.000000 6.000000 2.000000 2.000000 2.000000
 [265] 2.301754 2.000000 2.301754 2.000000 2.301754 3.000000 3.000000 2.000000
 [273] 2.000000 4.000000 3.000000 1.000000 4.000000 2.000000 2.301754 2.000000
 [281] 4.000000 2.301754 6.000000 2.000000 3.000000 1.000000 2.301754 2.000000
 [289] 2.000000 2.301754 1.000000 1.000000 3.000000 2.000000 3.000000 3.000000
 [297] 1.000000 2.301754 1.000000 4.000000 2.000000 1.000000 1.000000 3.000000
 [305] 2.000000 1.000000 2.000000 3.000000 1.000000 2.301754 2.000000 3.000000
 [313] 3.000000 2.000000 1.000000 2.000000 3.000000 5.000000 5.000000 1.000000
 [321] 2.000000 3.000000 3.000000 1.000000 2.301754 2.301754 1.000000 2.000000
 [329] 4.000000 2.301754 2.000000 1.000000 1.000000 1.000000 3.000000 2.000000
 [337] 1.000000 1.000000 3.000000 4.000000 2.301754 1.000000 2.000000 1.000000
 [345] 1.000000 3.000000 3.000000 2.301754 1.000000 1.000000 3.000000 5.000000
 [353] 3.000000 2.000000 3.000000 4.000000 1.000000 4.000000 3.000000 1.000000
 [361] 2.301754 2.000000 1.000000 2.000000 2.000000 1.000000 2.000000 2.000000
 [369] 6.000000 1.000000 2.000000 4.000000 5.000000 2.301754 3.000000 4.000000
 [377] 2.000000 1.000000 1.000000 4.000000 2.000000 1.000000 1.000000 1.000000
 [385] 1.000000 2.000000 1.000000 4.000000 4.000000 1.000000 3.000000 2.301754
 [393] 3.000000 3.000000 2.301754 2.000000 2.301754 1.000000 2.000000 1.000000
 [401] 1.000000 4.000000 2.000000 1.000000 4.000000 4.000000 2.301754 1.000000
 [409] 2.000000 2.301754 3.000000 2.000000 2.000000 2.000000 1.000000 4.000000
 [417] 3.000000 6.000000 1.000000 2.000000 3.000000 1.000000 3.000000 2.000000
 [425] 2.000000 2.000000 1.000000 1.000000 3.000000 2.000000 1.000000 1.000000
 [433] 1.000000 3.000000 2.000000 2.000000 2.301754 4.000000 4.000000 4.000000
 [441] 1.000000 1.000000 2.301754 4.000000 3.000000 2.301754 1.000000 3.000000
 [449] 1.000000 3.000000 2.000000 4.000000 2.000000 2.000000 2.000000 3.000000
 [457] 2.000000 1.000000 4.000000 3.000000 2.301754 1.000000 4.000000 3.000000
 [465] 1.000000 3.000000 2.000000 2.301754 3.000000 2.301754 1.000000 3.000000
 [473] 1.000000 4.000000 1.000000 1.000000 1.000000 2.000000 4.000000 3.000000
 [481] 1.000000 2.000000 2.000000 2.000000 3.000000 2.000000 3.000000 1.000000
 [489] 1.000000 2.301754 3.000000 2.000000 1.000000 1.000000 2.000000 2.301754
 [497] 2.000000 2.000000 2.000000 3.000000 3.000000 1.000000 1.000000 2.000000
 [505] 2.301754 1.000000 2.000000 1.000000 1.000000 3.000000 3.000000 1.000000
 [513] 3.000000 1.000000 1.000000 1.000000 1.000000 1.000000 2.000000 5.000000
 [521] 1.000000 1.000000 2.000000 2.000000 1.000000 1.000000 2.301754 1.000000
 [529] 4.000000 1.000000 2.000000 4.000000 1.000000 3.000000 2.000000 2.301754
 [537] 1.000000 1.000000 2.301754 2.000000 1.000000 1.000000 4.000000 2.000000
 [545] 3.000000 3.000000 1.000000 5.000000 3.000000 1.000000 1.000000 2.000000
 [553] 2.301754 1.000000 1.000000 3.000000 1.000000 3.000000 2.000000 4.000000
 [561] 2.301754 2.000000 3.000000 2.000000 1.000000 2.000000 1.000000 1.000000
 [569] 1.000000 2.000000 2.000000 3.000000 1.000000 5.000000 2.000000 2.301754
 [577] 2.000000 2.301754 3.000000 2.000000 2.000000 2.000000 1.000000 5.000000
 [585] 3.000000 2.000000 3.000000 1.000000 2.301754 3.000000 1.000000 2.000000
 [593] 2.000000 2.000000 1.000000 2.000000 2.000000 4.000000 2.301754 6.000000
 [601] 1.000000 2.000000 2.301754 1.000000 1.000000 2.000000 2.000000 3.000000
 [609] 2.301754 3.000000 2.000000 3.000000 3.000000 4.000000 2.000000 2.301754
 [617] 2.000000 2.301754 4.000000 2.301754 1.000000 1.000000 2.000000 2.000000
 [625] 3.000000 1.000000 1.000000 1.000000 3.000000 2.301754 2.000000 5.000000
 [633] 2.301754 7.000000 1.000000 2.301754 4.000000 3.000000 3.000000 1.000000
 [641] 2.301754 1.000000 1.000000 1.000000 1.000000 3.000000 2.000000 4.000000
 [649] 2.000000 2.000000 3.000000 2.301754 2.301754 1.000000 4.000000 3.000000
 [657] 2.000000 2.000000 2.000000 3.000000 2.000000 4.000000 2.000000 2.000000
 [665] 4.000000 2.301754 2.301754 2.301754 6.000000 3.000000 3.000000 1.000000
 [673] 4.000000 4.000000 2.000000 1.000000 2.301754 1.000000 6.000000 2.301754
 [681] 3.000000 3.000000 2.000000 1.000000 1.000000 6.000000 2.301754 1.000000
 [689] 5.000000 1.000000 2.301754 2.000000 6.000000 2.000000 2.301754 4.000000
 [697] 1.000000 3.000000 1.000000 2.000000 2.301754 1.000000 1.000000 3.000000
 [705] 1.000000 2.000000 4.000000 2.000000 1.000000 3.000000 2.000000 4.000000
 [713] 3.000000 2.000000 2.000000 1.000000 1.000000 5.000000 6.000000 4.000000
 [721] 2.000000 2.000000 2.000000 2.000000 4.000000 2.301754 1.000000 2.000000
 [729] 2.000000 2.000000 2.000000 4.000000 5.000000 2.301754 2.301754 2.301754
 [737] 4.000000 3.000000 3.000000 3.000000 2.000000 4.000000 2.000000 4.000000
 [745] 2.301754 2.301754 2.301754 2.301754 2.000000 1.000000 2.301754 2.000000
 [753] 4.000000 3.000000 2.000000 2.301754 2.000000 3.000000 1.000000 3.000000
 [761] 4.000000 2.301754 1.000000 2.000000 1.000000 2.000000 2.301754 3.000000
 [769] 1.000000 2.000000 1.000000 2.000000 1.000000 2.000000 1.000000 2.000000
 [777] 2.000000 2.000000 2.000000 1.000000 1.000000 3.000000 3.000000 1.000000
 [785] 3.000000 4.000000 3.000000 2.301754 2.301754 4.000000 2.000000 3.000000
 [793] 2.000000 1.000000 3.000000 2.000000 4.000000 2.000000 2.000000 3.000000
 [801] 1.000000 2.000000 4.000000 3.000000 3.000000 4.000000 2.301754 1.000000
 [809] 4.000000 2.000000 1.000000 1.000000 1.000000 3.000000 1.000000 5.000000
 [817] 2.000000 2.000000 4.000000 2.000000 2.301754 1.000000 3.000000 1.000000
 [825] 2.000000 2.301754 1.000000 2.000000 1.000000 2.000000 1.000000 2.301754
 [833] 1.000000 3.000000 2.000000 3.000000 2.000000 2.301754 2.000000 1.000000
 [841] 4.000000 2.000000 2.301754 2.301754 2.301754 2.000000 4.000000 2.000000
 [849] 2.301754 2.301754 3.000000 1.000000 2.301754 5.000000 5.000000 2.000000
 [857] 2.000000 2.000000 2.301754 2.000000 1.000000 3.000000 1.000000 3.000000
 [865] 2.000000 4.000000 2.000000 4.000000 2.301754 4.000000 1.000000 2.000000
 [873] 3.000000 2.000000 3.000000 3.000000 2.000000 3.000000 2.000000 2.000000
 [881] 2.000000 1.000000 3.000000 2.000000 4.000000 2.000000 2.301754 3.000000
 [889] 3.000000 2.000000 2.000000 2.301754 2.301754 3.000000 2.000000 1.000000
 [897] 2.000000 4.000000 1.000000 1.000000 1.000000 1.000000 4.000000 3.000000
 [905] 2.000000 2.301754 3.000000 2.000000 2.301754 1.000000 2.301754 3.000000
 [913] 2.000000 1.000000 1.000000 1.000000 2.000000 2.301754 2.000000 2.000000
 [921] 3.000000 3.000000 2.000000 2.301754 2.301754 4.000000 5.000000 2.000000
 [929] 2.000000 2.000000 1.000000 2.000000 3.000000 1.000000 3.000000 3.000000
 [937] 4.000000 3.000000 2.301754 1.000000 1.000000 1.000000 2.301754 4.000000
 [945] 3.000000 5.000000 1.000000 1.000000 2.000000 2.301754 2.000000 2.000000
 [953] 2.000000 2.000000 5.000000 2.000000 2.000000 3.000000 1.000000 2.000000
 [961] 3.000000 2.301754 1.000000 2.000000 2.301754 2.301754 2.000000 2.301754
 [969] 3.000000 1.000000 1.000000 2.000000 5.000000 3.000000 5.000000 1.000000
 [977] 1.000000 4.000000 2.301754 2.000000 1.000000 3.000000 1.000000 1.000000
 [985] 2.000000 4.000000 3.000000 3.000000 3.000000 2.301754 1.000000 1.000000
 [993] 2.000000 2.000000 1.000000 1.000000 2.000000 2.000000 2.301754 2.000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>stdev <span class="ot">&lt;-</span> <span class="fu">sd</span>(na_example, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>arr2 <span class="ot">&lt;-</span> na_example</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>arr2[<span class="fu">is.na</span>(na_example)] <span class="ot">&lt;-</span> stdev</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>arr2Str <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">'New Dataset With Standart Deviation Replacing NAs'</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(arr2Str)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "New Dataset With Standart Deviation Replacing NAs"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(arr2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   [1] 2.00000 1.00000 3.00000 2.00000 1.00000 3.00000 1.00000 4.00000 3.00000
  [10] 2.00000 2.00000 1.22338 2.00000 2.00000 1.00000 4.00000 1.22338 1.00000
  [19] 1.00000 2.00000 1.00000 2.00000 2.00000 1.00000 2.00000 5.00000 1.22338
  [28] 2.00000 2.00000 3.00000 1.00000 2.00000 4.00000 1.00000 1.00000 1.00000
  [37] 4.00000 5.00000 2.00000 3.00000 4.00000 1.00000 2.00000 4.00000 1.00000
  [46] 1.00000 2.00000 1.00000 5.00000 1.22338 1.22338 1.22338 1.00000 1.00000
  [55] 5.00000 1.00000 3.00000 1.00000 1.22338 4.00000 4.00000 7.00000 3.00000
  [64] 2.00000 1.22338 1.22338 1.00000 1.22338 4.00000 1.00000 2.00000 2.00000
  [73] 3.00000 2.00000 1.00000 2.00000 2.00000 4.00000 3.00000 4.00000 2.00000
  [82] 3.00000 1.00000 3.00000 2.00000 1.00000 1.00000 1.00000 3.00000 1.00000
  [91] 1.22338 3.00000 1.00000 2.00000 2.00000 1.00000 2.00000 2.00000 1.00000
 [100] 1.00000 4.00000 1.00000 1.00000 2.00000 3.00000 3.00000 2.00000 2.00000
 [109] 3.00000 3.00000 3.00000 4.00000 1.00000 1.00000 1.00000 2.00000 1.22338
 [118] 4.00000 3.00000 4.00000 3.00000 1.00000 2.00000 1.00000 1.22338 1.22338
 [127] 1.22338 1.22338 1.00000 5.00000 1.00000 2.00000 1.00000 3.00000 5.00000
 [136] 3.00000 2.00000 2.00000 1.22338 1.22338 1.22338 1.22338 3.00000 5.00000
 [145] 3.00000 1.00000 1.00000 4.00000 2.00000 4.00000 3.00000 3.00000 1.22338
 [154] 2.00000 3.00000 2.00000 6.00000 1.22338 1.00000 1.00000 2.00000 2.00000
 [163] 1.00000 3.00000 1.00000 1.00000 5.00000 1.22338 1.22338 2.00000 4.00000
 [172] 1.22338 2.00000 5.00000 1.00000 4.00000 3.00000 3.00000 1.22338 4.00000
 [181] 3.00000 1.00000 4.00000 1.00000 1.00000 3.00000 1.00000 1.00000 1.22338
 [190] 1.22338 3.00000 5.00000 2.00000 2.00000 2.00000 3.00000 1.00000 2.00000
 [199] 2.00000 3.00000 2.00000 1.00000 1.22338 2.00000 1.22338 1.00000 1.22338
 [208] 1.22338 2.00000 1.00000 1.00000 1.22338 3.00000 1.22338 1.00000 2.00000
 [217] 2.00000 1.00000 3.00000 2.00000 2.00000 1.00000 1.00000 2.00000 3.00000
 [226] 1.00000 1.00000 1.00000 4.00000 3.00000 4.00000 2.00000 2.00000 1.00000
 [235] 4.00000 1.00000 1.22338 5.00000 1.00000 4.00000 1.22338 3.00000 1.22338
 [244] 1.22338 1.00000 1.00000 5.00000 2.00000 3.00000 3.00000 2.00000 4.00000
 [253] 1.22338 3.00000 2.00000 5.00000 1.22338 2.00000 3.00000 4.00000 6.00000
 [262] 2.00000 2.00000 2.00000 1.22338 2.00000 1.22338 2.00000 1.22338 3.00000
 [271] 3.00000 2.00000 2.00000 4.00000 3.00000 1.00000 4.00000 2.00000 1.22338
 [280] 2.00000 4.00000 1.22338 6.00000 2.00000 3.00000 1.00000 1.22338 2.00000
 [289] 2.00000 1.22338 1.00000 1.00000 3.00000 2.00000 3.00000 3.00000 1.00000
 [298] 1.22338 1.00000 4.00000 2.00000 1.00000 1.00000 3.00000 2.00000 1.00000
 [307] 2.00000 3.00000 1.00000 1.22338 2.00000 3.00000 3.00000 2.00000 1.00000
 [316] 2.00000 3.00000 5.00000 5.00000 1.00000 2.00000 3.00000 3.00000 1.00000
 [325] 1.22338 1.22338 1.00000 2.00000 4.00000 1.22338 2.00000 1.00000 1.00000
 [334] 1.00000 3.00000 2.00000 1.00000 1.00000 3.00000 4.00000 1.22338 1.00000
 [343] 2.00000 1.00000 1.00000 3.00000 3.00000 1.22338 1.00000 1.00000 3.00000
 [352] 5.00000 3.00000 2.00000 3.00000 4.00000 1.00000 4.00000 3.00000 1.00000
 [361] 1.22338 2.00000 1.00000 2.00000 2.00000 1.00000 2.00000 2.00000 6.00000
 [370] 1.00000 2.00000 4.00000 5.00000 1.22338 3.00000 4.00000 2.00000 1.00000
 [379] 1.00000 4.00000 2.00000 1.00000 1.00000 1.00000 1.00000 2.00000 1.00000
 [388] 4.00000 4.00000 1.00000 3.00000 1.22338 3.00000 3.00000 1.22338 2.00000
 [397] 1.22338 1.00000 2.00000 1.00000 1.00000 4.00000 2.00000 1.00000 4.00000
 [406] 4.00000 1.22338 1.00000 2.00000 1.22338 3.00000 2.00000 2.00000 2.00000
 [415] 1.00000 4.00000 3.00000 6.00000 1.00000 2.00000 3.00000 1.00000 3.00000
 [424] 2.00000 2.00000 2.00000 1.00000 1.00000 3.00000 2.00000 1.00000 1.00000
 [433] 1.00000 3.00000 2.00000 2.00000 1.22338 4.00000 4.00000 4.00000 1.00000
 [442] 1.00000 1.22338 4.00000 3.00000 1.22338 1.00000 3.00000 1.00000 3.00000
 [451] 2.00000 4.00000 2.00000 2.00000 2.00000 3.00000 2.00000 1.00000 4.00000
 [460] 3.00000 1.22338 1.00000 4.00000 3.00000 1.00000 3.00000 2.00000 1.22338
 [469] 3.00000 1.22338 1.00000 3.00000 1.00000 4.00000 1.00000 1.00000 1.00000
 [478] 2.00000 4.00000 3.00000 1.00000 2.00000 2.00000 2.00000 3.00000 2.00000
 [487] 3.00000 1.00000 1.00000 1.22338 3.00000 2.00000 1.00000 1.00000 2.00000
 [496] 1.22338 2.00000 2.00000 2.00000 3.00000 3.00000 1.00000 1.00000 2.00000
 [505] 1.22338 1.00000 2.00000 1.00000 1.00000 3.00000 3.00000 1.00000 3.00000
 [514] 1.00000 1.00000 1.00000 1.00000 1.00000 2.00000 5.00000 1.00000 1.00000
 [523] 2.00000 2.00000 1.00000 1.00000 1.22338 1.00000 4.00000 1.00000 2.00000
 [532] 4.00000 1.00000 3.00000 2.00000 1.22338 1.00000 1.00000 1.22338 2.00000
 [541] 1.00000 1.00000 4.00000 2.00000 3.00000 3.00000 1.00000 5.00000 3.00000
 [550] 1.00000 1.00000 2.00000 1.22338 1.00000 1.00000 3.00000 1.00000 3.00000
 [559] 2.00000 4.00000 1.22338 2.00000 3.00000 2.00000 1.00000 2.00000 1.00000
 [568] 1.00000 1.00000 2.00000 2.00000 3.00000 1.00000 5.00000 2.00000 1.22338
 [577] 2.00000 1.22338 3.00000 2.00000 2.00000 2.00000 1.00000 5.00000 3.00000
 [586] 2.00000 3.00000 1.00000 1.22338 3.00000 1.00000 2.00000 2.00000 2.00000
 [595] 1.00000 2.00000 2.00000 4.00000 1.22338 6.00000 1.00000 2.00000 1.22338
 [604] 1.00000 1.00000 2.00000 2.00000 3.00000 1.22338 3.00000 2.00000 3.00000
 [613] 3.00000 4.00000 2.00000 1.22338 2.00000 1.22338 4.00000 1.22338 1.00000
 [622] 1.00000 2.00000 2.00000 3.00000 1.00000 1.00000 1.00000 3.00000 1.22338
 [631] 2.00000 5.00000 1.22338 7.00000 1.00000 1.22338 4.00000 3.00000 3.00000
 [640] 1.00000 1.22338 1.00000 1.00000 1.00000 1.00000 3.00000 2.00000 4.00000
 [649] 2.00000 2.00000 3.00000 1.22338 1.22338 1.00000 4.00000 3.00000 2.00000
 [658] 2.00000 2.00000 3.00000 2.00000 4.00000 2.00000 2.00000 4.00000 1.22338
 [667] 1.22338 1.22338 6.00000 3.00000 3.00000 1.00000 4.00000 4.00000 2.00000
 [676] 1.00000 1.22338 1.00000 6.00000 1.22338 3.00000 3.00000 2.00000 1.00000
 [685] 1.00000 6.00000 1.22338 1.00000 5.00000 1.00000 1.22338 2.00000 6.00000
 [694] 2.00000 1.22338 4.00000 1.00000 3.00000 1.00000 2.00000 1.22338 1.00000
 [703] 1.00000 3.00000 1.00000 2.00000 4.00000 2.00000 1.00000 3.00000 2.00000
 [712] 4.00000 3.00000 2.00000 2.00000 1.00000 1.00000 5.00000 6.00000 4.00000
 [721] 2.00000 2.00000 2.00000 2.00000 4.00000 1.22338 1.00000 2.00000 2.00000
 [730] 2.00000 2.00000 4.00000 5.00000 1.22338 1.22338 1.22338 4.00000 3.00000
 [739] 3.00000 3.00000 2.00000 4.00000 2.00000 4.00000 1.22338 1.22338 1.22338
 [748] 1.22338 2.00000 1.00000 1.22338 2.00000 4.00000 3.00000 2.00000 1.22338
 [757] 2.00000 3.00000 1.00000 3.00000 4.00000 1.22338 1.00000 2.00000 1.00000
 [766] 2.00000 1.22338 3.00000 1.00000 2.00000 1.00000 2.00000 1.00000 2.00000
 [775] 1.00000 2.00000 2.00000 2.00000 2.00000 1.00000 1.00000 3.00000 3.00000
 [784] 1.00000 3.00000 4.00000 3.00000 1.22338 1.22338 4.00000 2.00000 3.00000
 [793] 2.00000 1.00000 3.00000 2.00000 4.00000 2.00000 2.00000 3.00000 1.00000
 [802] 2.00000 4.00000 3.00000 3.00000 4.00000 1.22338 1.00000 4.00000 2.00000
 [811] 1.00000 1.00000 1.00000 3.00000 1.00000 5.00000 2.00000 2.00000 4.00000
 [820] 2.00000 1.22338 1.00000 3.00000 1.00000 2.00000 1.22338 1.00000 2.00000
 [829] 1.00000 2.00000 1.00000 1.22338 1.00000 3.00000 2.00000 3.00000 2.00000
 [838] 1.22338 2.00000 1.00000 4.00000 2.00000 1.22338 1.22338 1.22338 2.00000
 [847] 4.00000 2.00000 1.22338 1.22338 3.00000 1.00000 1.22338 5.00000 5.00000
 [856] 2.00000 2.00000 2.00000 1.22338 2.00000 1.00000 3.00000 1.00000 3.00000
 [865] 2.00000 4.00000 2.00000 4.00000 1.22338 4.00000 1.00000 2.00000 3.00000
 [874] 2.00000 3.00000 3.00000 2.00000 3.00000 2.00000 2.00000 2.00000 1.00000
 [883] 3.00000 2.00000 4.00000 2.00000 1.22338 3.00000 3.00000 2.00000 2.00000
 [892] 1.22338 1.22338 3.00000 2.00000 1.00000 2.00000 4.00000 1.00000 1.00000
 [901] 1.00000 1.00000 4.00000 3.00000 2.00000 1.22338 3.00000 2.00000 1.22338
 [910] 1.00000 1.22338 3.00000 2.00000 1.00000 1.00000 1.00000 2.00000 1.22338
 [919] 2.00000 2.00000 3.00000 3.00000 2.00000 1.22338 1.22338 4.00000 5.00000
 [928] 2.00000 2.00000 2.00000 1.00000 2.00000 3.00000 1.00000 3.00000 3.00000
 [937] 4.00000 3.00000 1.22338 1.00000 1.00000 1.00000 1.22338 4.00000 3.00000
 [946] 5.00000 1.00000 1.00000 2.00000 1.22338 2.00000 2.00000 2.00000 2.00000
 [955] 5.00000 2.00000 2.00000 3.00000 1.00000 2.00000 3.00000 1.22338 1.00000
 [964] 2.00000 1.22338 1.22338 2.00000 1.22338 3.00000 1.00000 1.00000 2.00000
 [973] 5.00000 3.00000 5.00000 1.00000 1.00000 4.00000 1.22338 2.00000 1.00000
 [982] 3.00000 1.00000 1.00000 2.00000 4.00000 3.00000 3.00000 3.00000 1.22338
 [991] 1.00000 1.00000 2.00000 2.00000 1.00000 1.00000 2.00000 2.00000 1.22338
[1000] 2.00000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>mean1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(arr1)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>mean2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(arr2)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>std1 <span class="ot">&lt;-</span> <span class="fu">sd</span>(arr1)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>std2 <span class="ot">&lt;-</span> <span class="fu">sd</span>(arr2)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">'Mean of Mean Replacing NAs'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mean of Mean Replacing NAs"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mean1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.301754</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">'Mean of StDev Replacing NAs'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mean of StDev Replacing NAs"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mean2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.14539</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">'StDev of Mean Replacing NAs'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "StDev of Mean Replacing NAs"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(std1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.131117</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">'StDev of StDev Replacing NAs'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "StDev of StDev Replacing NAs"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(std2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.193206</code></pre>
</div>
</div>
<p><u><strong>Comparison</strong></u></p>
<p>The mean of the original data-set is 2.30 meanwhile the standard deviation is 1.22.</p>
<p>The mean of the replacement of the NA’s with mean value (2.30) is 2.30 and the standard deviation is 1.13.</p>
<p>The mean of the replacement of the NA’s with standard devaition value (1.22) is 2.14 and the standard deviation is 1.19.</p>
<p>When we do the comparison i can say that the changing the NAs with a mean results in a same mean value as the original set but different standard deviations. This means that the center of the both data sets are the same (2.30) but the distance of these points to the center is different. In this case the points are located much closer to the center compared to the original set. Similarly when we compare the other set with the original we can say that the center point is different than the original set but the dispersion of the points are much closer to the original set.</p>
<p><u><strong>Decision</strong></u></p>
<p>I believe handling the missing data is more depends on what we are trying to achieve with our analysis. If we would like to see what central point is a better solution to our problem.For example we would like to place an access point to the neighborhoods of Ankara, we would choose to focus on the central location of the orders. For this problem i could replace the NAs with the mean. If the solution of the problem involves the dispersion of the points. For example if we would like to control the fragment damage of the milling machine, i would much focus on the dispersion of the fragments instead of their centers. For this problem i would rather choose replacing the NAs with the standard deviation.</p>


</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../assignments.html" class="pagination-link" aria-label="My Assignments">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">My Assignments</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../assignments/assignment-2.html" class="pagination-link" aria-label="Assignment 2">
        <span class="nav-page-text">Assignment 2</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Hacettepe IE - EMU660 - Spring 2025</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>